local_resinos:
  app-name: myproject
  build-triggers:
    - Dockerfile: 8df8f7034c746fadb9564e369ae748bed6ea3b939fb1dae351536aff83554936
  environment:
    - FOO=bar
destination: /usr/src/app
ignore:
  - .git
